name: Deploy Next.js app using Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'project-echo'
        zone: 'asia-southeast1-b'
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
        command: 'echo Hello-world'