name: Deploy Next.js app using Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH keys to authenticate with the server
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private SSH key in GitHub Secrets

      # Step 3: Ensure the server's SSH key is added to known_hosts
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Step 4: SSH into the server and run the deploy script
      - name: Run deploy script on server
        run: |
          ssh -o StrictHostKeyChecking=no {{secrets.SERVER_USER}}@${{ secrets.SERVER_IP }} "chmod +x /home/destucr/project-echo/deploy.sh && /home/destucr/project-echo/deploy.sh"
